from .airline import airline_router
from .airport import airport_router
from .auth import auth_router
from .checklist import checklist_router
from .crew import crew_router
from .delay import delay_router
from .flight import flight_router
from .plane import plane_router
from .probability import probability_router
from .report import report_router
from .reports_and_systems import report_and_systems_router
from .system import system_router
from .delay_prediction import delay_prediction_router